server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/html; # Matches the path inside the container

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass PHP scripts to FastCGI server (PHP-FPM container)
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # Uses the service name "php" as the hostname on port 9000
        fastcgi_pass php:9000; 
        
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
